---
- hosts: localhost
  connection: local
  vars:
    - username: devusops
    - home: /home/devusops
  tasks:
    - name: print variables
      debug:
        msg: "Username: {{ username }}, Home dir: {{ home }}"
